[package]
name = "firefly_alloc"
description = "Memory management, garbage collection, and fundamental allocator-aware types."
version = "0.1.0"
authors = ["Paul Schoenfelder <paulschoenfelder@gmail.com>"]
publish = false
edition = "2021"

[features]
default = []
std = ["firefly_binary/std"]

[dependencies]
firefly_binary = { path = "../binary" }
firefly_system = { path = "../system" }
static_assertions = "1.1"
thiserror = "1.0"

[dependencies.intrusive-collections]
version = "0.9"
features = ["nightly"]
