[package]
name = "liblumen_llvm"
version = "0.1.0"
authors = ["Paul Schoenfelder <paulschoenfelder@fastmail.com>"]
edition = "2018"

build = "build.rs"
links = "lumen_llvm_core"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
anyhow = "1.0"
fxhash = "0.2"
liblumen_session = { path = "../session" }
liblumen_target = { path = "../target" }
liblumen_util = { path = "../../liblumen_util" }
liblumen_compiler_macros = { path = "../macros" }
liblumen_profiling = { path = "../profiling" }

[build-dependencies]
cc = "1.0"
which = "2.0.1"
walkdir = "2.3"
