[package]
name = "firefly_syntax_erl"
version = "0.1.0"
authors = ["Paul Schoenfelder <paulschoenfelder@gmail.com>"]
readme = "README.md"
publish = false
edition = "2021"
license = "MIT OR Apache-2.0"

build = "build.rs"

[dependencies]
firefly_beam = { path = "../../library/beam" }
firefly_binary = { path = "../../library/binary" }
firefly_diagnostics = { path = "../diagnostics" }
firefly_intern = { path = "../intern" }
firefly_number = { path = "../../library/number" }
firefly_pass = { path = "../pass" }
firefly_parser = { path = "../parser" }
firefly_syntax_base = { path = "../syntax_base" }
firefly_syntax_core = { path = "../syntax_core" }
firefly_syntax_pp = { path = "../syntax_pp" }
firefly_util = { path = "../util" }

anyhow = "1.0"
either = "1.8"
itertools = "0.10"
lalrpop-util = "0.19"
lazy_static = "1.4"
log = "0.4"
paste = "1.0"
strsim = "0.10"
thiserror = "1.0"

[dependencies.smallvec]
version = "1.9"
features = ["union", "const_generics", "const_new", "specialization"]

[dev-dependencies]
pretty_assertions = "1.0"

[build-dependencies]
lalrpop = "0.19"
