task:
  name: Check Formatted
  container:
    image: kronicdeth/lumen-development@sha256:3c8581df91a902ce97762696103b008d1e10a59dd047fdbb200df3535c6dd3d0
  script: cargo fmt -- --check

x86_64_task_template: &x86_64_TASK_TEMPLATE
  build_script: cargo build
  # `*_test_script`s in order of crate dependency graph
  liblumen_arena_test_script: |
    cargo test -p liblumen_arena
  liblumen_core_test_script: |
    cargo test -p liblumen_core
  liblumen_alloc_test_script: |
    cargo test -p liblumen_alloc
  lumen_runtime_test_script: |
    cargo test -p lumen_rt_full
  liblumen_otp_test_script: |
    cargo test -p liblumen_otp
  lumen_interpreter_test_script: |
    cargo test -p lumen_interpreter
  examples_spawn_chain_test_script: |
    cargo test -p spawn-chain

task:
  name: Linux x86_64 libraries
  container:
    image: kronicdeth/lumen-development@sha256:3c8581df91a902ce97762696103b008d1e10a59dd047fdbb200df3535c6dd3d0
    cpu: 4
    memory: 12
  linux_x86_64_cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock
  << : *x86_64_TASK_TEMPLATE
  before_cache_script: rm -rf $CARGO_HOME/registry/index

task:
  name: Linux x86_64 compiler
  container:
    image: kronicdeth/lumen-development@sha256:3c8581df91a902ce97762696103b008d1e10a59dd047fdbb200df3535c6dd3d0
    cpu: 4
    memory: 12
  linux_x86_64_cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock
  make_build_script: |
    make build
  test_lumen_script: |
    cargo test -p lumen
  before_cache_script: rm -rf $CARGO_HOME/registry/index

task:
  name: macOS x86_64 libraries
  osx_instance:
    image: catalina-base
  env:
    LLVM_SYS_90_PREFIX: ${HOME}/clang+llvm-10.0.0-x86_64-apple-darwin19.3.0
    PATH: ${HOME}/.cargo/bin:${PATH}
  macos_x86_64_libraries_cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock
  install_llvm_script: |
    pushd $HOME
    wget https://github.com/lumen/llvm-project/releases/download/lumen-10.0.0-dev_2020-04-12/clang+llvm-10.0.0-x86_64-apple-darwin19.3.0.tar.gz
    tar xvfz clang+llvm-10.0.0-x86_64-apple-darwin19.3.0.tar.gz
    popd
  install_rustup_script: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain=nightly-2020-03-10
  <<: *x86_64_TASK_TEMPLATE
  before_cache_script: rm -rf $CARGO_HOME/registry/index

task:
  name: Linux wasm32
  container:
    image: kronicdeth/lumen-development@sha256:3c8581df91a902ce97762696103b008d1e10a59dd047fdbb200df3535c6dd3d0
    memory: 6
  linux_wasm32_cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock
  firefox_version_script: firefox --version
  gecko_driver_version_script: geckodriver --version
  liblumen_web_test_script: |
    wasm-pack test --headless --chrome --firefox native_implemented_functions/web
  examples_spawn_chain_build_script: |
    wasm-pack build examples/spawn-chain
  examples_spawn_chain_test_script: |
    wasm-pack test --headless --chrome --firefox examples/spawn-chain
  examples_spawn_chain_package_script: |
    pushd examples/spawn-chain
    pushd www
    npm install
    popd
    pushd pkg
    npm link
    popd
    pushd www
    npm link spawn-chain
    npm run build
    popd
    popd
  examples_spawn_chain_chain_artifacts:
    path: "examples/spawn-chain/www/dist/*"
  before_cache_script: rm -rf $CARGO_HOME/registry/index
