[package]
name = "firefly_syntax_ssa"
version = "0.1.0"
authors = ["Paul Schoenfelder <paulschoenfelder@gmail.com>"]
readme = "README.md"
publish = false
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
firefly_arena = { path = "../../library/arena" }
firefly_binary = { path = "../../library/binary" }
firefly_diagnostics = { path = "../diagnostics" }
firefly_intern = { path = "../intern" }
firefly_number = { path = "../../library/number" }
firefly_util = { path = "../util" }
firefly_syntax_base = { path = "../syntax_base" }

anyhow = "1.0"
cranelift-entity = "0.81"
paste = "1.0"

[dependencies.intrusive-collections]
version = "0.9"
features = ["nightly"]
