[package]
name = "liblumen_syntax_ssa"
version = "0.1.0"
authors = ["Paul Schoenfelder <paulschoenfelder@gmail.com>"]
readme = "README.md"
publish = false
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
liblumen_arena = { path = "../../library/arena" }
liblumen_binary = { path = "../binary" }
liblumen_diagnostics = { path = "../diagnostics" }
liblumen_intern = { path = "../intern" }
liblumen_number = { path = "../number" }
liblumen_util = { path = "../util" }
liblumen_syntax_base = { path = "../syntax_base" }

anyhow = "1.0"
cranelift-entity = "0.81"
paste = "1.0"

[dependencies.intrusive-collections]
version = "0.9"
features = ["nightly"]
