[package]
name = "firefly_syntax_ssa"
description = "Provides a high-level SSA intermediate representation used by the Firefly compiler"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow = { workspace = true, features = ["std"] }
cranelift-entity.workspace = true
firefly_arena = { path = "../../library/arena" }
firefly_binary = { path = "../../library/binary", features = ["std"] }
firefly_diagnostics = { path = "../diagnostics" }
firefly_intern = { path = "../intern", features = ["std"] }
firefly_number = { path = "../../library/number", features = ["std"] }
firefly_util = { path = "../util" }
firefly_syntax_base = { path = "../syntax_base" }
intrusive-collections.workspace = true
paste.workspace = true
