[package]
name = "lumen_rt_full"
version = "0.1.0"
authors = ["Paul Schoenfelder <paulschoenfelder@gmail.com>", "Luke Imhoff <Kronic.Deth@gmail.com>"]
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0"
bus = "2.2"
cfg-if = "1.0"
chrono = "0.4"
clap = "2.34"
colored = "2.0"
thiserror = "1.0"
lazy_static = "1.4"
libc = "0.2"
liblumen_core = { path = "../../library/core" }
liblumen_alloc = { path = "../../liblumen_alloc" }
log = "0.4"
lumen_rt_core = { path = "../core" }
num-bigint = "0.4"
num-traits = "0.2"
num_enum = "0.5"
rand = "0.8"
xorshift = "0.1"

[target.'cfg(unix)'.dependencies]
proptest = "1.0"
signal-hook = "0.3"

[target.'cfg(windows)'.dependencies]
proptest = "1.0"

# for debugging
[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3.56"
features = ['console']

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen = "0.2.79"
wasm-bindgen-test = "0.3.29"

[features]
time_web_sys = ["lumen_rt_core/time_web_sys"]
