[package]
name = "lumen_rt_full"
version = "0.1.0"
authors = ["Paul Schoenfelder <paulschoenfelder@gmail.com>", "Luke Imhoff <Kronic.Deth@gmail.com>"]
publish = false
edition = "2018"

[dependencies]
bus = "2.0"
cfg-if = "1.0"
clap = "2.32.0"
colored = "2.0"
anyhow = "1.0"
thiserror = "1.0"
lazy_static = "1.2"
libc = "0.2"
log = "0.4"
num-bigint = "0.3"
num-traits = "0.2"
num_enum = "0.5"
chrono = "0.4"

liblumen_core = { path = "../../liblumen_core" }
lumen_rt_core = { path = "../core" }
liblumen_alloc = { path = "../../liblumen_alloc" }

[dependencies.hashbrown]
version = "0.9"
features = ["nightly"]

[target.'cfg(unix)'.dependencies]
proptest = "1.0"
rand = "0.8"
signal-hook = "0.3"
xorshift = "0.1"

[target.'cfg(windows)'.dependencies]
proptest = "1.0"
rand = "0.8"
xorshift = "0.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
rand = { version = "0.8", features = ["getrandom"] }
xorshift = "0.1"

# for debugging
[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3.47"
features = ['console']

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen = "0.2.70"
wasm-bindgen-test = "0.3.17"

[features]
time_web_sys = ["lumen_rt_core/time_web_sys"]
