[package]
name = "lumen_rt_full"
version = "0.1.0"
authors = ["Paul Schoenfelder <paulschoenfelder@gmail.com>", "Luke Imhoff <Kronic.Deth@gmail.com>"]
publish = false
edition = "2018"

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
bus = "2.0"
cfg-if = "0.1.7"
clap = "2.32.0"
colored = "1.6"
anyhow = "1.0"
thiserror = "1.0"
lazy_static = "1.2"
libc = "0.2"
liblumen_alloc = { path = "../../liblumen_alloc" }
liblumen_core = { path = "../../liblumen_core" }
lumen_rt_core = { path = "../core" }
log = "0.4"
num-bigint = "0.2"
num-traits = "0.2"
num_enum = "0.4.2"
chrono = "0.4"

[dependencies.hashbrown]
version = "0.7"
features = ["nightly"]

[target.'cfg(unix)'.dependencies]
proptest = "0.9.3"
rand = "0.6"
signal-hook = "0.1"
xorshift = "0.1"

[target.'cfg(windows)'.dependencies]
proptest = "0.9.3"
rand = "0.6"
xorshift = "0.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
rand = { version = "0.6", features = ["wasm-bindgen"] }
xorshift = "0.1"

# for debugging
[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3.20"
features = ['console']

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen = "0.2.48"
wasm-bindgen-test = "0.2.48"

[features]
time_web_sys = ["lumen_rt_core/time_web_sys"]
