[package]
name = "firefly_syntax_pp"
version = "0.1.0"
authors = ["Paul Schoenfelder <paulschoenfelder@gmail.com>"]
readme = "README.md"
publish = false
edition = "2021"
license = "MIT OR Apache-2.0"

build = "build.rs"

[dependencies]
firefly_beam = { path = "../../library/beam" }
firefly_diagnostics = { path = "../diagnostics" }
firefly_intern = { path = "../intern" }
firefly_number = { path = "../../library/number" }
firefly_parser = { path = "../parser" }
firefly_util = { path = "../util" }
firefly_syntax_erl = { path = "../syntax_erl" }

anyhow = "1.0"
lalrpop-util = "0.19"
thiserror = "1.0"

[build-dependencies]
lalrpop = "0.19"
