[package]
name = "firefly_syntax_pp"
description = "Provides the Firefly compiler with a frontend for Erlang Abstract Format"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true
publish.workspace = true

build = "build.rs"

[dependencies]
anyhow = { workspace = true, features = ["std"] }
firefly_beam = { path = "../../library/beam" }
firefly_diagnostics = { path = "../diagnostics" }
firefly_intern = { path = "../intern", features = ["std"] }
firefly_number = { path = "../../library/number", features = ["std"] }
firefly_parser = { path = "../parser" }
firefly_util = { path = "../util" }
lalrpop-util.workspace = true
thiserror.workspace = true

[build-dependencies]
lalrpop.workspace = true
