[package]
name = "firefly_syntax_kernel"
description = "Provides a high-level, pre-SSA intermediate representation used for pattern matching/optimization for the Firefly compiler"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow = { workspace = true, features = ["std"] }
cranelift-entity.workspace = true
firefly_binary = { path = "../../library/binary", features = ["std"] }
firefly_diagnostics = { path = "../diagnostics" }
firefly_intern = { path = "../intern", features = ["std"] }
firefly_number = { path = "../../library/number", features = ["std"] }
firefly_pass = { path = "../pass" }
firefly_syntax_base = { path = "../syntax_base" }
firefly_syntax_ssa = { path = "../syntax_ssa" }
firefly_syntax_core = { path = "../syntax_core" }
firefly_util = { path = "../util" }
log.workspace = true
thiserror.workspace = true
rpds = { workspace = true, features = ["std"] }
smallvec.workspace = true
