[package]
name = "firefly_syntax_kernel"
version = "0.1.0"
authors = ["Paul Schoenfelder <paulschoenfelder@gmail.com>"]
readme = "README.md"
publish = false
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
firefly_binary = { path = "../../library/binary" }
firefly_diagnostics = { path = "../diagnostics" }
firefly_intern = { path = "../intern" }
firefly_number = { path = "../../library/number" }
firefly_pass = { path = "../pass" }
firefly_syntax_base = { path = "../syntax_base" }
firefly_syntax_ssa = { path = "../syntax_ssa" }
firefly_syntax_core = { path = "../syntax_core" }
firefly_util = { path = "../util" }

anyhow = "1.0"
cranelift-entity = "0.81"
log = "0.4"
thiserror = "1.0"
rpds = "0.12"
