[package]
name = "firefly_rt"
description = "The core runtime library, providing fundamental types and functionality"
version = "0.1.0"
authors = ["Paul Schoenfelder <paulschoenfelder@gmail.com>"]
publish = false
edition = "2021"

[features]
default = ["std"]
std = ["anyhow/std", "backtrace/std", "num-bigint/std", "rpds/std", "termcolor", "thiserror", "firefly_binary/std", "firefly_alloc/std"]
no_std = ["lazy_static/spin_no_std", "thiserror-no-std"]

[dependencies]
cfg-if = "1.0"
hashbrown = "0.12"
lazy_static = "1.4"
firefly_alloc = { path = "../alloc" }
firefly_arena = { path = "../arena" }
firefly_system = { path = "../system" }
firefly_binary = { path = "../binary" }
firefly_number = { path = "../number" }
paste = "1.0"
rustc-demangle = "0.1"
seq-macro = "0.3"
static_assertions = "1.1"

[dependencies.anyhow]
version = "1.0"
default-features = false

[dependencies.backtrace]
version = "0.3.66"
default-features = false

[dependencies.num-bigint]
version = "0.4"
default-features = false

[dependencies.num-traits]
version = "0.2"
default-features = false
features = ["i128"]

[dependencies.rpds]
version = "0.11"
default-features = false

[dependencies.thiserror]
version = "1.0"
optional = true

[dependencies.thiserror-no-std]
version = "2.0"
optional = true

[dependencies.termcolor]
version = "1.1.3"
optional = true

[build-dependencies]
toml = { version = "0.5", features = ["preserve_order"] }
Inflector = "0.11"
