[package]
name = "firefly_rt"
description = "The core runtime library, providing fundamental types and functionality"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true
publish.workspace = true

[features]
default = ["no_std"]
std = ["dep:flurry", "dep:termcolor", "dep:libloading", "anyhow/std", "backtrace/std", "firefly_alloc/std", "firefly_binary/std", "firefly_number/std", "rpds/std"]
no_std = ["dep:crossbeam-skiplist"]
async = []

[dependencies]
anyhow.workspace = true
backtrace.workspace = true
bitflags.workspace = true
cfg-if.workspace = true
crossbeam = "0.8"
crossbeam-skiplist = { version = "0.1", optional = true }
firefly_alloc = { path = "../alloc" }
firefly_arena = { path = "../arena" }
firefly_system = { path = "../system" }
firefly_binary = { path = "../binary", default-features = false }
firefly_bytecode = { path = "../bytecode" }
firefly_number = { path = "../number", default-features = false }
firefly_macros_seq = { path = "../../macros/seq" }
flurry = { version = "0.4", optional = true }
glidesort = { version = "0.1", features = ["unstable"] }
hashbrown.workspace = true
intrusive-collections.workspace = true
libloading = { version = "0.7", optional = true }
log.workspace = true
rpds.workspace = true
paste.workspace = true
rustc-demangle = "0.1"
rustc-hash.workspace = true
smallvec.workspace = true
static_assertions.workspace = true
termcolor = { version = "1.1", optional = true }

[build-dependencies]
toml.workspace = true
Inflector.workspace = true
