[package]
name = "liblumen_rt"
description = "The core runtime library, providing fundamental types and functionality"
version = "0.1.0"
authors = ["Paul Schoenfelder <paulschoenfelder@gmail.com>"]
publish = false
edition = "2021"

[features]
default = ["std"]
std = ["anyhow/std", "backtrace/std", "num-bigint/std", "rpds/std"]

[dependencies]
cfg-if = "1.0"
hashbrown = "0.12"
lazy_static = "1.4"
liblumen_alloc = { path = "../alloc" }
liblumen_arena = { path = "../arena" }
liblumen_system = { path = "../system" }
liblumen_binary = { path = "../../compiler/binary" }
paste = "1.0"
seq-macro = "0.3"
static_assertions = "1.1"

[dependencies.anyhow]
version = "1.0"
default-features = false

[dependencies.backtrace]
version = "0.3"
default-features = false

[dependencies.num-bigint]
version = "0.4"
default-features = false

[dependencies.num-traits]
version = "0.2"
default-features = false
features = ["i128"]

[dependencies.rpds]
version = "0.11"
default-features = false


[build-dependencies]
toml = { version = "0.5", features = ["preserve_order"] }
Inflector = "0.11"
