[package]
name = "liblumen_web"
version = "0.1.0"
authors = ["Luke Imhoff <Kronic.Deth@gmail.com>"]
edition = "2021"
publish = false
description = "Lumen bindings for Web APIs"

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
anyhow = "1.0.11"
js-sys = "0.3.25"
liblumen_alloc = { path = "../../liblumen_alloc" }
liblumen_otp = { path = "../otp" }
lumen_rt_full = { path = "../../runtimes/full" }
panic-control = "0.1.4"
native_implemented = { path = "../macro" }

[dependencies.lumen_rt_core]
path = "../../runtimes/core"
features = ["time_web_sys"]

[dependencies.wasm-bindgen]
version = "0.2.48"
features = ["nightly"]

[dependencies.web-sys]
version = "0.3.47"
features = ["Document", "DomException", "Element", "Event", "EventListener", "EventTarget", "HtmlCollection",
            "HtmlBodyElement", "HtmlElement", "HtmlFormElement", "HtmlInputElement", "HtmlTableElement", "Node", "Text",
            "WebSocket", "Window"]

[dev-dependencies]
wasm-bindgen-futures = "0.4.17"
wasm-bindgen-test = "0.3.17"
