[package]
name = "liblumen_syntax_base"
version = "0.1.0"
authors = ["Paul Schoenfelder <paulschoenfelder@gmail.com>"]
readme = "README.md"
publish = false
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
liblumen_binary = { path = "../binary" }
liblumen_compiler_macros = { path = "../macros" }
liblumen_diagnostics = { path = "../diagnostics" }
liblumen_intern = { path = "../intern" }
liblumen_number = { path = "../number" }

bitflags = "1.3"
lazy_static = "1.4"
rpds = "0.12"
thiserror = "1.0"
