[package]
name = "firefly-make"
version = "0.1.0"
description = "Support tool for Firefly"
authors = ["Paul Schoenfelder <paulschoenfelder@gmail.com>"]
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0"
cargo_metadata = "0.15"
clap = { version = "3.2", features = ["derive", "env"] }
lit = { git = "https://github.com/getfirefly/lit", branch = "erlang" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
walkdir = "*"
