[package]
name = "firefly_util"
description = "Assorted utility functions used across various components of the Firefly compiler"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
cfg-if.workspace = true
anyhow = { workspace = true, features = ["std"] }
thiserror.workspace = true
libc = { workspace = true, features = ["std"] }
glob = "0.3"
atty = "0.2"
firefly_diagnostics = { path = "../diagnostics" }
parking_lot.workspace = true
