[package]
name = "liblumen_mlir"
version = "0.1.0"
authors = ["Paul Schoenfelder <paulschoenfelder@fastmail.com>"]
edition = "2018"

build = "build.rs"
links = "lumen_mlir_core"

[lib]
crate-type = ["rlib", "staticlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
anyhow = "1.0"
liblumen_llvm = { path = "../llvm" }
liblumen_session = { path = "../session" }
liblumen_target = { path = "../target" }
liblumen_util = { path = "../../liblumen_util" }
liblumen_compiler_macros = { path = "../macros" }

[build-dependencies]
cc = "1.0"
walkdir = "2.3"
liblumen_llvm = { path = "../llvm" }
