[package]
name = "firefly_emulator"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
crate-type = ["staticlib"]

[features]

[dependencies]
crossbeam = "0.8"
dirs = "4.0"
env_logger.workspace = true
firefly_arena = { path = "../../library/arena" }
firefly_alloc = { path = "../../library/alloc" }
firefly_binary = { path = "../../library/binary", features = ["std"] }
firefly_bytecode = { path = "../../library/bytecode", features = ["std"] }
firefly_crt = { path = "../crt", default-features = false, features = ["std"] }
firefly_system = { path = "../../library/system" }
firefly_number = { path = "../../library/number", features = ["std"] }
firefly_rt = { path = "../../library/rt", default-features = false, features = ["std"] }
intrusive-collections.workspace = true
log.workspace = true
smallvec = { version = "1.9", features = ["union", "const_generics", "const_new", "specialization", "write"] }
rustc-hash.workspace = true

[target.'cfg(not(target_family = "wasm"))'.dependencies]
signal-hook = "0.3"
libc.workspace = true
tokio = { version = "1.21", features = ["full", "tracing", "test-util"] }

[target.'cfg(target_family = "wasm")'.dependencies]
tokio = { version = "1.21" }
