[package]
name = "stackmaps"
description = "Provides an implementation of stack maps for use by the Firefly compiler and runtime"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
cfg-if.workspace = true
lazy_static.workspace = true
hashbrown.workspace = true
