[package]
authors = ["Paul Schoenfelder <paulschoenfelder@fastmail.com>"]
name = "panic"
version = "0.1.0"
edition = "2018"

[lib]
test = false
bench = false
doc = false

[dependencies]
libc = "0.2"
cfg-if = "1.0"

[target.'cfg(target_arch = "wasm32")'.dependencies.unwind]
path = "../unwind"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.unwind]
path = "../unwind"
features = ["llvm-libunwind"]
