[package]
name = "firefly_rt_tiny"
version = "0.1.0"
authors = ["Paul Schoenfelder <paulschoenfelder@fastmail.com>"]
publish = false
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
anyhow = "1.0"
bus = "2.2"
dirs = "4.0"
signal-hook = "0.3"
libc = "0.2"

firefly_arena = { path = "../../library/arena" }
firefly_alloc = { path = "../../library/alloc" }
firefly_binary = { path = "../../library/binary" }
firefly_number = { path = "../../library/number" }
firefly_crt = { path = "../crt" }
firefly_rt = { path = "../../library/rt" }

[dependencies.smallvec]
version = "1.9"
features = ["union", "const_generics", "const_new", "specialization"]
