[package]
authors = ["Paul Schoenfelder <paulschoenfelder@fastmail.com>"]
name = "unwind"
version = "0.1.0"
build = "build.rs"
edition = "2018"

[lib]
test = false
bench = false
doc = false

[dependencies]
cfg-if = "1.0"
libc = "0.2"

[build-dependencies]
cc = "1.0"

[features]
llvm-libunwind = []
