#[path = "erlang/add_2.rs"]
pub mod add_2;
#[path = "erlang/and_2.rs"]
pub mod and_2;
#[path = "erlang/andalso_2.rs"]
pub mod andalso_2;
#[path = "erlang/atom_to_binary_2.rs"]
pub mod atom_to_binary_2;
#[path = "erlang/atom_to_list_1.rs"]
pub mod atom_to_list_1;
#[path = "erlang/display_1.rs"]
pub mod display_1;
#[path = "erlang/or_2.rs"]
pub mod or_2;
