#[path = "erlang/add_2.rs"]
pub mod add_2;
#[path = "erlang/and_2.rs"]
pub mod and_2;
#[path = "erlang/andalso_2.rs"]
pub mod andalso_2;
#[path = "erlang/atom_to_binary_2.rs"]
pub mod atom_to_binary_2;
#[path = "erlang/atom_to_list_1.rs"]
pub mod atom_to_list_1;
#[path = "erlang/binary_part_2.rs"]
pub mod binary_part_2;
#[path = "erlang/binary_part_3.rs"]
pub mod binary_part_3;
#[path = "erlang/binary_to_integer_1.rs"]
pub mod binary_to_integer_1;
#[path = "erlang/binary_to_integer_2.rs"]
pub mod binary_to_integer_2;
#[path = "erlang/binary_to_list_1.rs"]
pub mod binary_to_list_1;
#[path = "erlang/binary_to_list_3.rs"]
pub mod binary_to_list_3;
#[path = "erlang/binary_to_term_1.rs"]
pub mod binary_to_term_1;
#[path = "erlang/binary_to_term_2.rs"]
pub mod binary_to_term_2;
#[path = "erlang/cancel_timer_1.rs"]
pub mod cancel_timer_1;
#[path = "erlang/ceil_1.rs"]
pub mod ceil_1;
#[path = "erlang/convert_time_unit_3.rs"]
pub mod convert_time_unit_3;
#[path = "erlang/display_1.rs"]
pub mod display_1;
#[path = "erlang/or_2.rs"]
pub mod or_2;
