[package]
name = "firefly_session"
version = "0.1.0"
authors = ["Paul Schoenfelder <paulschoenfelder@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0"
clap = "2.34"
log = "0.4"
thiserror = "1.0"

firefly_compiler_macros = { path = "../macros" }
firefly_diagnostics = { path = "../diagnostics" }
firefly_intern = { path = "../intern" }
firefly_target = { path = "../target" }
firefly_util = { path = "../util" }
firefly_syntax_pp = { path = "../syntax_pp" }
firefly_parser = { path = "../parser" }
