[package]
name = "liblumen_session"
version = "0.1.0"
authors = ["Paul Schoenfelder <paulschoenfelder@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
anyhow = "1.0"
clap = "2.33.0"
codespan = "0.9.3"
codespan-reporting = "0.9.3"
log = "0.4"
termcolor = "1.1.0"
thiserror = "1.0"

liblumen_compiler_macros = { path = "../macros" }
liblumen_target = { path = "../target" }
liblumen_util = { path = "../../liblumen_util" }

libeir_syntax_erl = { git = "https://github.com/eirproject/eir", branch = "lumen" }
libeir_ir = { git = "https://github.com/eirproject/eir", branch = "lumen" }
