[package]
name = "liblumen_session"
version = "0.1.0"
authors = ["Paul Schoenfelder <paulschoenfelder@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0"
clap = "2.34"
log = "0.4"
thiserror = "1.0"
logos = "0.12"
logos-derive = "0.12"

liblumen_compiler_macros = { path = "../macros" }
liblumen_intern = { path = "../intern" }
liblumen_target = { path = "../target" }
liblumen_util = { path = "../../liblumen_util" }
