[package]
name = "liblumen_syntax_core"
version = "0.1.0"
authors = ["Paul Schoenfelder <paulschoenfelder@gmail.com>"]
readme = "README.md"
publish = false
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0"
bitflags = "1.3"
cranelift-entity = "0.81"
lazy_static = "1.4"
liblumen_arena = { path = "../library/arena" }
liblumen_binary = { path = "../binary" }
liblumen_compiler_macros = { path = "../macros" }
liblumen_diagnostics = { path = "../diagnostics" }
liblumen_intern = { path = "../intern" }
liblumen_number = { path = "../number" }
liblumen_util = { path = "../util" }
paste = "1.0"
thiserror = "1.0"

[dependencies.intrusive-collections]
version = "0.9"
features = ["nightly"]
