[package]
name = "firefly_syntax_core"
description = "Provides a high-level, extended lambda calculus intermediate representation for the Firefly compiler"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow = { workspace = true, features = ["std"] }
firefly_binary = { path = "../../library/binary", features = ["std"] }
firefly_diagnostics = { path = "../diagnostics" }
firefly_intern = { path = "../intern", features = ["std"] }
firefly_pass = { path = "../pass" }
firefly_syntax_base = { path = "../syntax_base" }
firefly_util = { path = "../util" }
rpds = { workspace = true, features = ["std"] }
