[package]
name = "firefly_syntax_core"
version = "0.1.0"
authors = ["Paul Schoenfelder <paulschoenfelder@gmail.com>"]
readme = "README.md"
publish = false
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
firefly_binary = { path = "../../library/binary" }
firefly_diagnostics = { path = "../diagnostics" }
firefly_intern = { path = "../intern" }
firefly_pass = { path = "../pass" }
firefly_syntax_base = { path = "../syntax_base" }
firefly_util = { path = "../util" }

anyhow = "1.0"
rpds = "0.12"
