#[path = "erlang/abs_1.rs"]
pub mod abs_1;
#[path = "erlang/add_2.rs"]
pub mod add_2;
#[path = "erlang/and_2.rs"]
pub mod and_2;
#[path = "erlang/andalso_2.rs"]
pub mod andalso_2;
#[path = "erlang/append_element_2.rs"]
pub mod append_element_2;
#[path = "erlang/apply_2.rs"]
pub mod apply_2;
#[path = "erlang/atom_to_binary_2.rs"]
pub mod atom_to_binary_2;
#[path = "erlang/atom_to_list_1.rs"]
pub mod atom_to_list_1;
#[path = "erlang/band_2.rs"]
pub mod band_2;
#[path = "erlang/binary_part_2.rs"]
pub mod binary_part_2;
#[path = "erlang/binary_part_3.rs"]
pub mod binary_part_3;
#[path = "erlang/binary_to_integer_1.rs"]
pub mod binary_to_integer_1;
#[path = "erlang/binary_to_integer_2.rs"]
pub mod binary_to_integer_2;
#[path = "erlang/binary_to_list_1.rs"]
pub mod binary_to_list_1;
#[path = "erlang/binary_to_list_3.rs"]
pub mod binary_to_list_3;
#[path = "erlang/binary_to_term_1.rs"]
pub mod binary_to_term_1;
#[path = "erlang/binary_to_term_2.rs"]
pub mod binary_to_term_2;
#[path = "erlang/bnot_1.rs"]
pub mod bnot_1;
#[path = "erlang/bor_2.rs"]
pub mod bor_2;
#[path = "erlang/bsl_2.rs"]
pub mod bsl_2;
#[path = "erlang/bsr_2.rs"]
pub mod bsr_2;
#[path = "erlang/bxor_2.rs"]
pub mod bxor_2;
#[path = "erlang/cancel_timer_1.rs"]
pub mod cancel_timer_1;
#[path = "erlang/cancel_timer_2.rs"]
pub mod cancel_timer_2;
#[path = "erlang/ceil_1.rs"]
pub mod ceil_1;
#[path = "erlang/concatenate_2.rs"]
pub mod concatenate_2;
#[path = "erlang/convert_time_unit_3.rs"]
pub mod convert_time_unit_3;
#[path = "erlang/date_0.rs"]
pub mod date_0;
#[path = "erlang/delete_element_2.rs"]
pub mod delete_element_2;
#[path = "erlang/demonitor_1.rs"]
pub mod demonitor_1;
#[path = "erlang/demonitor_2.rs"]
pub mod demonitor_2;
#[path = "erlang/display_1.rs"]
pub mod display_1;
#[path = "erlang/div_2.rs"]
pub mod div_2;
#[path = "erlang/divide_2.rs"]
pub mod divide_2;
#[path = "erlang/element_2.rs"]
pub mod element_2;
#[path = "erlang/erase_0.rs"]
pub mod erase_0;
#[path = "erlang/erase_1.rs"]
pub mod erase_1;
#[path = "erlang/error_1.rs"]
pub mod error_1;
#[path = "erlang/error_2.rs"]
pub mod error_2;
#[path = "erlang/exit_1.rs"]
pub mod exit_1;
#[path = "erlang/float_1.rs"]
pub mod float_1;
#[path = "erlang/float_to_binary_1.rs"]
pub mod float_to_binary_1;
#[path = "erlang/float_to_binary_2.rs"]
pub mod float_to_binary_2;
#[path = "erlang/float_to_list_1.rs"]
pub mod float_to_list_1;
#[path = "erlang/float_to_list_2.rs"]
pub mod float_to_list_2;
#[path = "erlang/floor_1.rs"]
pub mod floor_1;
#[path = "erlang/function_exported_3.rs"]
pub mod function_exported_3;
#[path = "erlang/get_0.rs"]
pub mod get_0;
#[path = "erlang/get_1.rs"]
pub mod get_1;
#[path = "erlang/get_keys_0.rs"]
pub mod get_keys_0;
#[path = "erlang/get_keys_1.rs"]
pub mod get_keys_1;
#[path = "erlang/hd_1.rs"]
pub mod hd_1;
#[path = "erlang/integer_to_binary_1.rs"]
pub mod integer_to_binary_1;
#[path = "erlang/integer_to_list_1.rs"]
pub mod integer_to_list_1;
#[path = "erlang/is_alive_0.rs"]
pub mod is_alive_0;
#[path = "erlang/is_atom_1.rs"]
pub mod is_atom_1;
#[path = "erlang/is_binary_1.rs"]
pub mod is_binary_1;
#[path = "erlang/is_list_1.rs"]
pub mod is_list_1;
#[path = "erlang/link_1.rs"]
pub mod link_1;
#[path = "erlang/or_2.rs"]
pub mod or_2;
#[path = "erlang/process_flag_2.rs"]
pub mod process_flag_2;
#[path = "erlang/spawn_1.rs"]
pub mod spawn_1;
#[path = "erlang/spawn_3.rs"]
pub mod spawn_3;
#[path = "erlang/spawn_link_1.rs"]
pub mod spawn_link_1;
#[path = "erlang/spawn_link_3.rs"]
pub mod spawn_link_3;
#[path = "erlang/spawn_monitor_1.rs"]
pub mod spawn_monitor_1;
#[path = "erlang/spawn_monitor_3.rs"]
pub mod spawn_monitor_3;
#[path = "erlang/spawn_opt_2.rs"]
pub mod spawn_opt_2;
#[path = "erlang/spawn_opt_4.rs"]
pub mod spawn_opt_4;
#[path = "erlang/tl_1.rs"]
pub mod tl_1;
