[package]
name = "liblumen_parser"
version = "0.1.0"
authors = ["Hans Elias B. Josephsen <me@hansihe.com>", "Paul Schoenfelder <paulschoenfelder@gmail>"]
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
liblumen_diagnostics = { path = "../diagnostics" }
thiserror = "1.0"

[dev-dependencies]
pretty_assertions = "1.0"
