[package]
name = "liblumen_profiling"
version = "0.1.0"
authors = ["Paul Schoenfelder <paulschoenfelder@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
cfg-if = "1.0"
anyhow = "1.0"
log = "0.4"
fxhash = "0.2"
parking_lot = "0.11.1"
byteorder = "1.3"
bitflags = "1.2"

[target.'cfg(not(target_arch="wasm32"))'.dependencies]
memmap = "0.7"
