[package]
name = "firefly_profiling"
description = "Provides profiling functionality for the Firefly compiler"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow = { workspace = true, features = ["std"] }
bitflags.workspace = true
byteorder.workspace = true
cfg-if.workspace = true
fxhash.workspace = true
log.workspace = true
parking_lot.workspace = true

[target.'cfg(not(target_arch="wasm32"))'.dependencies]
memmap = "0.7"
