[package]
name = "firefly_beam"
version = "0.1.0"
authors = ["Paul Schoenfelder <paulschoenfelder@gmail.com>", "Luke Imhoff <Kronic.Deth@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
firefly_intern = { path = "../../compiler/intern" }
firefly_number = { path = "../number" }

anyhow = "1.0"
thiserror = "1.0"
byteorder = "1.2"
libflate = "0.1"
