[package]
name = "firefly-lld"
version = "0.1.0"
description = "The linker bundled with Firefly toolchains"
authors = ["Paul Schoenfelder <paulschoenfelder@gmail.com>"]
publish = false
edition = "2021"
