name: wasm32-unknown-unknown (macOS)

on: push

env:
  TOOLCHAIN: nightly-2021-02-28

jobs:
  wasm:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.TOOLCHAIN }}
          override: true
      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ github.workflow }}-${{ github.job }}-toolchain-${{ env.TOOLCHAIN }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-make
      - name: Cache LLVM
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: ~/.local/share/llvm/lumen
          key: lumen-12.0.0-dev_2020-10-22-apple-darwin19.5.0
      - name: Install LLVM
        if: steps.cache-llvm.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.local/share/llvm
          pushd ~/.local/share/llvm
          wget https://github.com/lumen/llvm-project/releases/download/lumen-12.0.0-dev_2020-10-22/clang+llvm-12.0.0-x86_64-apple-darwin19.5.0.tar.gz
          tar xvfz clang+llvm-12.0.0-x86_64-apple-darwin19.5.0.tar.gz
          mv clang+llvm-12.0.0-x86_64-apple-darwin19.5.0 lumen
          popd
      - name: Set LLVM_PREFIX
        run: echo "LLVM_PREFIX=$HOME/.local/share/llvm/lumen" >> $GITHUB_ENV
      - name: Install Ninja
        run: brew install ninja
      - name: Test Lumen Web
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: test-web -- --chrome --firefox --safari
      - name: Test Spawn Chain
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: test-spawn-chain-wasm -- --firefox --safari
