name: wasm32-unknown-unknown (Linux)

on: push

jobs:
  wasm:
    runs-on: ubuntu-latest
    container:
      image: kronicdeth/lumen-development@sha256:7cabc638118f2bae7aecc74c9b48fc89e9c862303d2b18b3c448d998d4e95228

    steps:
      - uses: actions/checkout@v2
      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ github.workflow }}-${{ github.job }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      # $HOME is owned by user id 1001.  `container` `options` `--user 1001` doesn't work because dependencies can't be
      # installed, so make root own the directory instead, so that Firefox doesn't complain that root is using a profile
      # for a different user.
      - name: Own Home
        run: chown -R $(whoami) $HOME
      - name: Build TableGen
        run: make lumen-tblgen
      - name: Lumen Web Test
        run: wasm-pack test --headless --chrome --firefox native_implemented/web
      - name: Interpreter Checkout
        run: git clone --depth 1 https://github.com/lumen/interpreter interpreter
      - name: Examples Checkout
        run: |
          git init examples
          cd examples
          git remote add origin https://github.com/lumen/examples
          git fetch --no-tags --prune --progress --depth=1 origin +bf390b117c02d58f33eeacca4b203769103c9ea7:refs/remotes/origin/spawn-chain-cli
          git checkout --progress --force -B spawn-chain-cli refs/remotes/origin/spawn-chain-cli
      - name: Spawn Chain Build
        run: wasm-pack build examples/spawn-chain/wasm
      - name: Spawn Chain Test
        run: wasm-pack test --headless --chrome --firefox examples/spawn-chain/wasm
