name: wasm32-unknown-unknown (Linux)

on: push

env:
  TOOLCHAIN: nightly-2021-02-28

jobs:
  wasm:
    runs-on: ubuntu-latest
    container:
      image: kronicdeth/lumen-development@sha256:fa3b5af44249c8f1e4f03485584f1343089120eeb6766c97e6010fdd39ddafbc

    steps:
      - uses: actions/checkout@v2
      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ github.workflow }}-${{ github.job }}-toolchain-${{ env.TOOLCHAIN }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      # $HOME is owned by user id 1001.  `container` `options` `--user 1001` doesn't work because dependencies can't be
      # installed, so make root own the directory instead, so that Firefox doesn't complain that root is using a profile
      # for a different user.
      - name: Own Home
        run: chown -R $(whoami) $HOME
      - name: Lumen Web Test
        run: cargo make test-web -- --chrome --firefox
      - name: Spawn Chain Test
        run: cargo make test-spawn-chain-wasm -- --firefox
