name: x86_64-unknown-linux-gnu compiler

on: push

jobs:
  compiler:
    runs-on: ubuntu-latest
    container: kronicdeth/lumen-development@sha256:594e15875ec350fb08433b4508a8eba8a234203a4b280ac049f262f1f101c672

    steps:
      - uses: actions/checkout@v2
      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-libraries-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-libraries-cargo-index-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-libraries-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
      - name: Make Build
        env:
          RUST_BACKTRACE: full
        run: make build
      - name: Lumen Test
        run: cargo test --package lumen
