name: x86_64-apple-darwin Runtime Full

on: push

jobs:
  runtime:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install nightly-2020-05-13
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2020-05-13
          override: true
      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ github.workflow }}-${{ github.job }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache LLVM
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: ~/.local/share/llvm/lumen
          key: lumen-12.0.0-dev_2020-08-26-apple-darwin19.5.0
      - name: Install LLVM
        if: steps.cache-llvm.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.local/share/llvm
          pushd ~/.local/share/llvm
          wget https://github.com/lumen/llvm-project/releases/download/lumen-12.0.0-dev_2020-08-26/clang+llvm-12.0.0-x86_64-apple-darwin19.5.0.tar.gz
          tar xvfz clang+llvm-12.0.0-x86_64-apple-darwin19.5.0.tar.gz
          mv clang+llvm-12.0.0-x86_64-apple-darwin19.5.0 lumen
          popd
      - name: Set LLVM_PREFIX
        run: echo "::set-env name=LLVM_PREFIX::$HOME/.local/share/llvm/lumen"
      - name: Install Ninja
        run: brew install ninja
      - name: Make Build
        env:
          RUST_BACKTRACE: full
        run: make build-shared
      - name: Test lumen_rt_full
        run: cargo test --package lumen_rt_full
      - name: Test liblumen_otp with runtime_full
        run: cargo test --package liblumen_otp
