name: x86_64-unknown-linux-gnu compiler

on: push

env:
  TOOLCHAIN: nightly-2021-02-28

jobs:
  compiler:
    runs-on: ubuntu-latest
    container: kronicdeth/lumen-development@sha256:fa3b5af44249c8f1e4f03485584f1343089120eeb6766c97e6010fdd39ddafbc

    steps:
      - uses: actions/checkout@v2
      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ github.workflow }}-${{ github.job }}-toolchain-${{ env.TOOLCHAIN }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build Compiler
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: lumen
      - name: Add Compiler To Path
        run: |
          if [ -n "${GITHUB_PATH}" ]; then
            echo "$PWD/bin" >> $GITHUB_PATH
          else
            echo "::add-path::${PWD}/bin"
          fi
      - name: Run baseline tests
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: test -- --package lumen
      - name: Run liblumen_otp integration tests
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: |
            test -- --package liblumen_otp lib:: -- --skip lumen::otp
      - name: Run spawn-chain tests
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: test-spawn-chain
