name: x86_64-unknown-linux-gnu Runtime Full

on: push

jobs:
  runtime:
    runs-on: ubuntu-latest
    container: kronicdeth/lumen-development@sha256:bb25b47f31e25caf1ff66ed9e7b920a9986fa643873deb9d72f727bca6812987

    steps:
      - uses: actions/checkout@v2
      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ github.workflow }}-${{ github.job }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Make Build
        run: make build-shared
      - name: Test lumen_rt_full
        run: cargo test --package lumen_rt_full --no-fail-fast
      - name: Test liblumen_otp with runtime_full
        run: "cargo test --package liblumen_otp --no-fail-fast -- --skip lib:: --skip lumen::otp"
