name: x86_64-unknown-linux-gnu firefly/otp

on: push

env:
  TOOLCHAIN: nightly-2022-07-12

jobs:
  firefly-otp:
    if: ${{ false }} # disable
    runs-on: ubuntu-latest
    container: kronicdeth/lumen-development@sha256:2809805464d685940b58765a634fa23a5fd1a62c65710cfa43a8791cd50fbecd

    steps:
      - uses: actions/checkout@v2
      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ github.workflow }}-${{ github.job }}-toolchain-${{ env.TOOLCHAIN }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build Compiler
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: firefly
      - name: firefly/otp Checkout
        run: |
          cd ..
          git init otp
          cd otp
          echo "ERL_TOP=$PWD" >> $GITHUB_ENV
          git remote add origin https://github.com/firefly/otp
          git fetch --no-tags --prune --progress --depth=1 origin +f97de7a99692cb08b5e27d17e86d92707ad16eed:refs/remotes/origin/firefly
          git checkout --progress --force -B firefly refs/remotes/origin/firefly
      - name: firefly/otp autoconf
        run: |
          cd ../otp
          ./otp_build autoconf
      - name: firefly/otp configure
        run: |
          cd ../otp
          ./configure
      - name: Test compiling firefly/otp against firefly_otp
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: |
            test -- --package firefly_otp firefly::otp::
