name: x86_64-unknown-linux-gnu Runtime Full

on: push

env:
  TOOLCHAIN: nightly-2021-02-28

jobs:
  runtime:
    runs-on: ubuntu-latest
    container: kronicdeth/lumen-development@sha256:fa3b5af44249c8f1e4f03485584f1343089120eeb6766c97e6010fdd39ddafbc

    steps:
      - uses: actions/checkout@v2
      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ github.workflow }}-${{ github.job }}-toolchain-${{ env.TOOLCHAIN }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build Compiler
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: lumen
      - name: Run lumen_rt_full tests
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: |
            test -- --package lumen_rt_full
      - name: Run liblumen_otp tests with runtime_full
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: |
            test -- --package liblumen_otp -- --skip lib:: --skip lumen::otp
