name: x86_64-apple-darwin Libraries

on: push

env:
  TOOLCHAIN: nightly-2022-07-12

jobs:
  libraries:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v2
      - name: Install nightly-2022-07-12
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.TOOLCHAIN }}
          override: true
      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ github.workflow }}-${{ github.job }}-toolchain-${{ env.TOOLCHAIN }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-make
      - name: Cache LLVM
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: ~/.local/share/llvm/firefly
          key: firefly-15.0.0-dev_2022-07-22-apple-darwin21.5.0
      - name: Install LLVM
        if: steps.cache-llvm.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.local/share/llvm
          pushd ~/.local/share/llvm
          wget https://github.com/lumen/llvm-project/releases/download/firefly-15.0.0-dev_2022-07-22/clang+llvm-15.0.0-x86_64-apple-darwin21.5.0.tar.gz
          tar xvfz clang+llvm-15.0.0-x86_64-apple-darwin21.5.0.tar.gz
          mv clang+llvm-15.0.0-x86_64-apple-darwin21.5.0 firefly
          popd
      - name: Set LLVM_PREFIX
        run: echo "LLVM_PREFIX=$HOME/.local/share/llvm/firefly" >> $GITHUB_ENV
      - name: Install Ninja
        run: brew install ninja
      - name: firefly_arena
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: test -- --package firefly_arena
      - name: firefly_alloc
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: test -- --package firefly_alloc
      - name: firefly_binary
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: test -- --package firefly_binary
      - name: firefly_system
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: test -- --package firefly_system
      - name: firefly_rt
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: test -- --package firefly_rt
