name: x86_64-unknown-linux-gnu compiler

on: push

jobs:
  compiler:
    runs-on: ubuntu-latest
    container: kronicdeth/lumen-development@sha256:c784a8eeb79fa5244bd15d408e469dc37b9e538b44f9b40fa4a20fd6c72c5f47

    steps:
      - uses: actions/checkout@v2
      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ github.workflow }}-${{ github.job }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Make Build
        env:
          RUST_BACKTRACE: full
        run: make build-shared
      - name: Lumen Test
        run: cargo test --package lumen --no-fail-fast
