name: x86_64-apple-darwin compiler

on: push

env:
  EPOCH: 0
  FIREFLY_BUILD_TYPE: static
  LLVM_LINK_LLVM_DYLIB: OFF
  LLVM_VERSION: 15.0.7
  TOOLCHAIN: nightly-2022-11-02

jobs:
  compiler:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.TOOLCHAIN }}
          override: true
      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ github.workflow }}-${{ github.job }}-toolchain-${{ env.TOOLCHAIN }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-make
      - name: Cache LLVM
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: ~/.local/share/llvm/firefly
          key: llvm-15.0.7
      - name: Install LLVM
        if: steps.cache-llvm.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.local/share/llvm
          pushd ~/.local/share/llvm
          wget "https://github.com/llvm/llvm-project/releases/download/llvmorg-${LLVM_VERSION}/clang+llvm-${LLVM_VERSION}-x86_64-apple-darwin21.0.tar.xz"
          tar -xzf "clang+llvm-${LLVM_VERSION}-x86_64-apple-darwin21.0.tar.xz"
          mv "clang+llvm-${LLVM_VERSION}-x86_64-apple-darwin21.0" firefly
          popd
      - name: Set LLVM_PREFIX
        run: echo "LLVM_PREFIX=$HOME/.local/share/llvm/firefly" >> $GITHUB_ENV
      - name: Install Ninja
        run: brew install ninja
      - name: Build Compiler
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: firefly
      - name: Add Compiler To Path
        run: |
          if [ -n "${GITHUB_PATH}" ]; then
            echo "$PWD/bin" >> $GITHUB_PATH
          else
            echo "::add-path::${PWD}/bin"
          fi
      - name: Run compiler unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args:
          - "-p"
          - "firefly_intern"
          - "-p"
          - "firefly_parser"
          - "-p"
          - "firefly_target"
          - "-p"
          - "firefly_syntax_erl"
          - "-p"
          - "firefly_syntax_pp"
      - name: Run literate tests
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: test-lit
