name: x86_64-unknown-linux-gnu Runtime Full

on: push

jobs:
  runtime:
    runs-on: ubuntu-latest
    container: kronicdeth/lumen-development@sha256:2809805464d685940b58765a634fa23a5fd1a62c65710cfa43a8791cd50fbecd

    steps:
      - uses: actions/checkout@v2
      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ github.workflow }}-${{ github.job }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build Compiler
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: lumen
      - name: Run lumen_rt_full tests
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: |
            test -- --package lumen_rt_full
      - name: Run liblumen_otp tests with runtime_full
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: |
            test -- --package liblumen_otp -- --skip lib:: --skip lumen::otp
