name: x86_64-apple-darwin Libraries

on: push

jobs:
  libraries:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install nightly-2020-05-13
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2020-05-13
          override: true
      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ github.workflow }}-${{ github.job }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache LLVM
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: ~/.local/share/llvm/lumen
          key: lumen-12.0.0-dev_2020-10-22-apple-darwin19.5.0
      - name: Install LLVM
        if: steps.cache-llvm.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.local/share/llvm
          pushd ~/.local/share/llvm
          wget https://github.com/lumen/llvm-project/releases/download/lumen-12.0.0-dev_2020-10-22/clang+llvm-12.0.0-x86_64-apple-darwin19.5.0.tar.gz
          tar xvfz clang+llvm-12.0.0-x86_64-apple-darwin19.5.0.tar.gz
          mv clang+llvm-12.0.0-x86_64-apple-darwin19.5.0 lumen
          popd
      - name: Set LLVM_PREFIX
        run: echo "LLVM_PREFIX=$HOME/.local/share/llvm/lumen" >> $GITHUB_ENV
      - name: Install Ninja
        run: brew install ninja
      - name: Test liblumen_arena
        run: cargo test --package liblumen_arena --no-fail-fast
      - name: Test liblumen_core
        run: cargo test --package liblumen_core --no-fail-fast
      - name: Build TableGen
        run: make lumen-tblgen
      - name: Test liblumen_alloc
        run: cargo test --package liblumen_alloc --no-fail-fast
