name: x86_64-apple-darwin lumen/otp

on: push

env:
  TOOLCHAIN: nightly-2021-02-28

jobs:
  lumen-otp:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install nightly-2021-02-28
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.TOOLCHAIN }}
          override: true
      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ github.workflow }}-${{ github.job }}-toolchain-${{ env.TOOLCHAIN }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-make
      - name: Cache LLVM
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: ~/.local/share/llvm/lumen
          key: lumen-12.0.0-dev_2020-10-22-apple-darwin19.5.0
      - name: Install LLVM
        if: steps.cache-llvm.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.local/share/llvm
          pushd ~/.local/share/llvm
          wget https://github.com/lumen/llvm-project/releases/download/lumen-12.0.0-dev_2020-10-22/clang+llvm-12.0.0-x86_64-apple-darwin19.5.0.tar.gz
          tar xvfz clang+llvm-12.0.0-x86_64-apple-darwin19.5.0.tar.gz
          mv clang+llvm-12.0.0-x86_64-apple-darwin19.5.0 lumen
          popd
      - name: Set LLVM_PREFIX
        run: echo "LLVM_PREFIX=$HOME/.local/share/llvm/lumen" >> $GITHUB_ENV
      - name: Install Ninja
        run: brew install ninja
      - name: Build Compiler
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: lumen
      - name: lumen/otp Checkout
        run: |
          cd ..
          git init otp
          cd otp
          echo "ERL_TOP=$PWD" >> $GITHUB_ENV
          git remote add origin https://github.com/lumen/otp
          git fetch --no-tags --prune --progress --depth=1 origin +ca83f680aab717fe65634247d16f18a8cbfc6d8d:refs/remotes/origin/lumen
          git checkout --progress --force -B lumen refs/remotes/origin/lumen
      - name: lumen/otp autoconf
        run: |
          cd ../otp
          ./otp_build autoconf
      - name: lumen/otp configure
        run: |
          cd ../otp
          ./configure
      - name: Install Erlang
        run: brew install erlang
      - name: Test compiling lumen/otp against liblumen_otp
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: |
            test -- --package liblumen_otp lumen::otp::
