name: x86_64-unknown-linux-gnu compiler

on: push

jobs:
  compiler:
    runs-on: ubuntu-latest
    container: kronicdeth/lumen-development@sha256:b81891c150f8176d41ee6959d6c5bffda43e626c2882405ba3199f97bac55a93

    steps:
      - uses: actions/checkout@v2
      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ github.workflow }}-${{ github.job }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Make Build
        env:
          RUST_BACKTRACE: full
        run: |
          make build-shared
          echo "$PWD/bin" >> $GITHUB_PATH
      - name: Lumen Test
        run: cargo test --package lumen --no-fail-fast
      - name: liblumen_otp Integration Tests
        run: "cargo test --package liblumen_otp lib:: -- --skip lumen::otp"
      - name: Examples Checkout
        run: |
          git init examples
          cd examples
          git remote add origin https://github.com/lumen/examples
          git fetch --no-tags --no-tags --prune --progress --depth=1 origin +bf390b117c02d58f33eeacca4b203769103c9ea7:refs/remotes/origin/spawn-chain-cli
          git checkout --progress --force -B spawn-chain-cli refs/remotes/origin/spawn-chain-cli
      - name: Spawn Chain Test
        working-directory: examples/spawn-chain/cli
        run: make test
